idf_component_register(
    SRCS
        "main.cpp"
        "../../components/lumos_doorbell/src/doorbell_transmitter.cpp"
        "../../components/lumos_doorbell/src/doorbell_platform_idf.cpp"
    INCLUDE_DIRS
        "."
        "../../components/lumos_doorbell/include"
    REQUIRES
        nvs_flash
        esp_event
        esp_netif
        esp_wifi
        esp_http_server
        esp_timer
        driver
        lumos_core
        lumos_ota
        app_update
        mdns
        json
        lwip
)
